# Background and foreground colors
background = #000000
foreground = #d3ee00

# Standard colors
palette = 0=#000000
palette = 1=#b85e4f
palette = 2=#55a737
palette = 3=#737200
palette = 4=#6066ff
palette = 5=#d400e4
palette = 6=#558170
palette = 7=#d3ee00

# Bright colors
palette = 8=#5a5852
palette = 9=#e7826f
palette = 10=#71d32a
palette = 11=#989a00
palette = 12=#8483ff
palette = 13=#fe4eff
palette = 14=#76a993
palette = 15=#d8f900
